package npm

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/sairintechnologycom/pkgsafe/internal/policy"
)

// ────────────────────────────────────────────────────────────────────────────
// pnpm-lock.yaml tests
// ────────────────────────────────────────────────────────────────────────────

func TestAnalyzePnpmLockfile_SafePackages(t *testing.T) {
	path := filepath.Join("..", "..", "..", "testdata", "npm", "pnpm-lock.yaml")
	res, err := AnalyzePnpmLockfile(path, policy.Default())
	if err != nil {
		t.Fatalf("AnalyzePnpmLockfile error: %v", err)
	}
	if res.Decision == "BLOCK" {
		t.Errorf("expected ALLOW or WARN for safe pnpm lockfile, got BLOCK; reasons: %v", res.Reasons)
	}
}

func TestAnalyzePnpmLockfile_ParsesPackages(t *testing.T) {
	path := filepath.Join("..", "..", "..", "testdata", "npm", "pnpm-lock.yaml")
	res, err := AnalyzePnpmLockfile(path, policy.Default())
	if err != nil {
		t.Fatalf("AnalyzePnpmLockfile error: %v", err)
	}
	// The lockfile_summary suspicious entry must mention ≥3 packages.
	found := false
	for _, s := range res.Suspicious {
		if strings.HasPrefix(s, "lockfile_summary:total:") {
			// Should have total:3 for the 3 packages in the fixture.
			if strings.Contains(s, "total:3") {
				found = true
			}
		}
	}
	if !found {
		t.Errorf("expected lockfile_summary:total:3 in Suspicious, got: %v", res.Suspicious)
	}
}

func TestAnalyzePnpmLockfile_BlockedPackage(t *testing.T) {
	pol := policy.Default()
	pol.BlockedPackages.NPM = []string{"lodash"}

	path := filepath.Join("..", "..", "..", "testdata", "npm", "pnpm-lock.yaml")
	res, err := AnalyzePnpmLockfile(path, pol)
	if err != nil {
		t.Fatalf("AnalyzePnpmLockfile error: %v", err)
	}
	foundBlocked := false
	for _, r := range res.Reasons {
		if r.ID == "blocked_package" && strings.Contains(r.Evidence, "lodash") {
			foundBlocked = true
		}
	}
	if !foundBlocked {
		t.Errorf("expected blocked_package reason for lodash, got: %v", res.Reasons)
	}
}

func TestAnalyzePnpmLockfile_EmptyFile(t *testing.T) {
	// Write a minimal pnpm lockfile with zero packages.
	dir := t.TempDir()
	empty := filepath.Join(dir, "pnpm-lock.yaml")
	if err := writeFile(empty, []byte("lockfileVersion: '6.0'\n\npackages:\n")); err != nil {
		t.Fatal(err)
	}
	res, err := AnalyzePnpmLockfile(empty, policy.Default())
	if err != nil {
		t.Fatalf("AnalyzePnpmLockfile error: %v", err)
	}
	// An empty lockfile should not score above 0 and should ALLOW.
	if res.Score > 0 {
		t.Errorf("expected score 0 for empty pnpm lockfile, got %d; reasons: %v", res.Score, res.Reasons)
	}
	if res.Decision == "BLOCK" {
		t.Errorf("expected ALLOW for empty pnpm lockfile, got BLOCK")
	}
}

// ────────────────────────────────────────────────────────────────────────────
// yarn.lock tests
// ────────────────────────────────────────────────────────────────────────────

func TestAnalyzeYarnLockfile_SafePackages(t *testing.T) {
	path := filepath.Join("..", "..", "..", "testdata", "npm", "yarn.lock")
	res, err := AnalyzeYarnLockfile(path, policy.Default())
	if err != nil {
		t.Fatalf("AnalyzeYarnLockfile error: %v", err)
	}
	if res.Decision == "BLOCK" {
		t.Errorf("expected ALLOW or WARN for safe yarn lockfile, got BLOCK; reasons: %v", res.Reasons)
	}
}

func TestAnalyzeYarnLockfile_ParsesPackages(t *testing.T) {
	path := filepath.Join("..", "..", "..", "testdata", "npm", "yarn.lock")
	res, err := AnalyzeYarnLockfile(path, policy.Default())
	if err != nil {
		t.Fatalf("AnalyzeYarnLockfile error: %v", err)
	}
	found := false
	for _, s := range res.Suspicious {
		if strings.HasPrefix(s, "lockfile_summary:total:") && strings.Contains(s, "total:3") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected lockfile_summary:total:3 in Suspicious, got: %v", res.Suspicious)
	}
}

func TestAnalyzeYarnLockfile_BlockedPackage(t *testing.T) {
	pol := policy.Default()
	pol.BlockedPackages.NPM = []string{"express"}

	path := filepath.Join("..", "..", "..", "testdata", "npm", "yarn.lock")
	res, err := AnalyzeYarnLockfile(path, pol)
	if err != nil {
		t.Fatalf("AnalyzeYarnLockfile error: %v", err)
	}
	foundBlocked := false
	for _, r := range res.Reasons {
		if r.ID == "blocked_package" && strings.Contains(r.Evidence, "express") {
			foundBlocked = true
		}
	}
	if !foundBlocked {
		t.Errorf("expected blocked_package reason for express, got: %v", res.Reasons)
	}
}

func TestAnalyzeYarnLockfile_EmptyFile(t *testing.T) {
	dir := t.TempDir()
	empty := filepath.Join(dir, "yarn.lock")
	if err := writeFile(empty, []byte("# THIS IS AN AUTOGENERATED FILE.\n# yarn lockfile v1\n\n")); err != nil {
		t.Fatal(err)
	}
	res, err := AnalyzeYarnLockfile(empty, policy.Default())
	if err != nil {
		t.Fatalf("AnalyzeYarnLockfile error: %v", err)
	}
	// An empty lockfile should not score above 0 and should ALLOW.
	if res.Score > 0 {
		t.Errorf("expected score 0 for empty yarn lockfile, got %d; reasons: %v", res.Score, res.Reasons)
	}
	if res.Decision == "BLOCK" {
		t.Errorf("expected ALLOW for empty yarn lockfile, got BLOCK")
	}
}

// ────────────────────────────────────────────────────────────────────────────
// pnpm v8 format (name@ver: keys without leading slash)
// ────────────────────────────────────────────────────────────────────────────

func TestAnalyzePnpmLockfile_V8Format(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "pnpm-lock.yaml")
	content := `lockfileVersion: '9.0'

packages:
  lodash@4.17.21:
    resolution: {integrity: sha512-abc==}
  react@18.2.0:
    resolution: {integrity: sha512-def==}
`
	if err := writeFile(p, []byte(content)); err != nil {
		t.Fatal(err)
	}
	res, err := AnalyzePnpmLockfile(p, policy.Default())
	if err != nil {
		t.Fatalf("error: %v", err)
	}
	// Should parse 2 packages and not block for known-safe packages.
	found := false
	for _, s := range res.Suspicious {
		if strings.Contains(s, "total:2") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected total:2 packages parsed from v8 format, got: %v", res.Suspicious)
	}
}

// ────────────────────────────────────────────────────────────────────────────
// writeFile helper (avoids import of io/ioutil)
// ────────────────────────────────────────────────────────────────────────────

func writeFile(path string, data []byte) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.Write(data)
	return err
}
